language:
  - cpp

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-5
    - g++-5

compiler:
    - gcc
    
before_install:
# Install cmake 3.10.0rc1 version
  - mkdir ${TRAVIS_BUILD_DIR}/cmake 
  - cd ${TRAVIS_BUILD_DIR}/cmake
  - wget -O cmake.sh https://cmake.org/files/v3.10/cmake-3.10.0-rc1-Linux-x86_64.sh    
  - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=${TRAVIS_BUILD_DIR}/cmake >> log.txt
  - cd ${TRAVIS_BUILD_DIR}
# Update
  - sudo apt-get update

install:

# OpenCV v3.4.0 with conttribs install code (modified from orignal source: https://github.com/jayrambhia/Install-OpenCV)

  # OpenCV dependencies - Details available at: http://docs.opencv.org/trunk/doc/tutorials/introduction/linux_install/linux_install.html
  - sudo apt-get install -y build-essential > log.txt
  - sudo apt-get install -y cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev >> log.txt
  - sudo apt-get install -y python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev >> log.txt

  # Download opencv-conttrib v3.4.0 .zip file and extract.
  - curl -sL https://github.com/opencv/opencv_contrib/archive/3.4.0.zip > opencv.zip
  - unzip opencv.zip >> log.txt
  
  # Download opencv v3.4.0 .zip file and extract.
  - curl -sL https://github.com/opencv/opencv/archive/3.4.0.zip > opencv.zip
  - unzip opencv.zip >> log.txt
  - rm opencv.zip
  - cd opencv-3.4.0
  
  # Create a new 'build' folder.
  - mkdir build
  - cd build
  
  # Set build instructions for Ubuntu distro.
  - ${TRAVIS_BUILD_DIR}/cmake/bin/cmake --version
  - ${TRAVIS_BUILD_DIR}/cmake/bin/cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=ON -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=ON -D WITH_QT=ON -D WITH_OPENGL=ON -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-3.4.0/modules .. >> ${TRAVIS_BUILD_DIR}/log.txt
  
  # Run 'make' with four threads.
  - make -j16
  
  # Install to OS.
  - sudo make install >> ${TRAVIS_BUILD_DIR}/log.txt
  
  # Add configuration to OpenCV to tell it where the library files are located on the file system (/usr/local/lib)
  - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf' >> ${TRAVIS_BUILD_DIR}/log.txt
  
  - sudo ldconfig >> ${TRAVIS_BUILD_DIR}/log.txt
  - echo "OpenCV installed."
  
  # We need to return to the repo "root" folder, so we can then 'cd' into the C++ project folder.
  - cd ${TRAVIS_BUILD_DIR}

script:
  - mkdir build
  - cd build
  - ${TRAVIS_BUILD_DIR}/cmake/bin/cmake ..
  - make